spring:
  application:
    name: hiresmart

  datasource:
    url: jdbc:postgresql://ep-round-tooth-a4727s0r-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_VbN9hLd1WFpS
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3
      embedding:
        model: nomic-embed-text

server:
  port: 8080
